### ISSUE TITLE
Editor freezes on start/takes too long to load

### ISSUE THREAD

**Issue by cvertee** [blurymind/YarnClassic#275]
When starting an editor you can sometimes see nodes but can't drag or edit them, only after some time they become available. Or on start you see nothing and the only option you have is to wait, but much longer time than in previous versions (0.4.124 for example).

**Comment by blurymind** [comment]
are you by any chance using any other language than english in the settings?

**Comment by cvertee** [comment]
Yeah, changin story language from Russian to English helped

**Comment by blurymind** [comment]
This is the same issue then. Its all because of using that dictionary
library locks it up while loading some languages.

**Comment by cvertee** [comment]
Hm as i see updating spell check setting loads dictionary again, maybe not load dictionaries on start while spell check is disabled?

**Comment by cvertee** [comment]
maybe something like this will work?
```this.setLanguage = function(language, e) {
    const languageId = e ? e.target.value : language;
    if (self.settings.spellcheckEnabled())
      load_dictionary(self.settings.language().split('-')[0]);
    const event = new CustomEvent('yarnSetLanguage');
    event.language = languageId;
    window.dispatchEvent(event);
  };
```

**Comment by blurymind** [comment]
Can you make a pr :) potentially could help us close both this and the
other issue

**Comment by FaultyFunctions** [comment]
Would it be possible to load the dictionary asynchronously to avoid freezing altogether?

**Comment by blurymind** [comment]
Its not the loading speed, but rather the library parsing the dictionary
locking up yarn. I would welcome a pr if someone comes up with a way around
it

**Comment by blurymind** [comment]
closing, this was fixed a while ago. Please reopen if it persists
