### ISSUE TITLE
Live Web APP not working.

### ISSUE THREAD

**Issue by sijmenvb** [blurymind/YarnClassic#301]
The live web app seems not to be working, it just gives the background. 

I hope this will be fixed soon, I used this editor and the .json it exported to make some tools for making **simple** dialogue and the web editor is ideal for that.

**Comment by blurymind** [comment]
can you re-test this please? Obviously the app has moved address now :)

**Comment by blurymind** [comment]
cant reproduce

**Comment by sijmenvb** [comment]
yes it was working again for a while now. (although i did have to clear my site data for it to work since the new update.)
