### ISSUE TITLE
mac osx use file type extension

### ISSUE THREAD

**Issue by desplesda** [blurymind/YarnClassic#31]
<a href="https://github.com/HawkenKing"><img src="https://avatars0.githubusercontent.com/u/5999766?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [HawkenKing](https://github.com/HawkenKing)**
_Monday Mar 28, 2016 at 08:54 GMT_
_Originally opened as https://github.com/InfiniteAmmoInc/Yarn/issues/31_

----

saving currently doesn't append any file type. Would be nice to have:

"test.json" instead of "test"

**Comment by desplesda** [comment]
<a href="https://github.com/blurymind"><img src="https://avatars0.githubusercontent.com/u/6495061?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [blurymind](https://github.com/blurymind)**
_Friday Jun 22, 2018 at 09:10 GMT_

----

This is probably fixed in the electron port (looks like a framework bug),
https://github.com/InfiniteAmmoInc/Yarn/pull/68
but I still havent made a mac build, also I dont have a mac to test with

I will try to build it in the weekend, but you will have to test it

**Comment by blurymind** [comment]
this has been fixed for ages now
