### ISSUE TITLE
Save (Ctrl-S) converts yarn dialogue structure into json and can't open it afterwards

### ISSUE THREAD

**Issue by AlekFy** [blurymind/YarnClassic#320]
I have a long dialogue in yarn structure
When I open it with the editor and make a change and then save it with Ctrl-S the file gets converted to json structure
The file name is still the same, but the size is 10kb heavier
If I try to open it with the editor afterwards, the file looks empty (no nodes visible on workspace)
If I save it again, the file is 0kb

But if I edit the original yarn file, save it with Ctrl-S but do not close the editor and then Save As Yarn -> the new file keeps the yarn structure and size, but the original one is getting converted

I wish the editor would save the file in a format it was written in, not json by default, all the more so given that the converted file can't be opened with editor to convert back :(

I have now checked and even if I save to GIST the file keeps converting to json :((
This problem goes back to at least ver 0.4.100

**Comment by blurymind** [comment]
yikes, that sounds bad. Think its possible that you are hitting the localStorage limit of 5mb.

Can you zip a file that we can use to stress test yarn. I will try to come up with a fix that handles running out of memory

**Comment by AlekFy** [comment]
Sure, here it is: 
[thenest_story.zip](https://github.com/blurymind/YarnClassic/files/13461494/thenest_story.zip)

**Comment by blurymind** [comment]
Thank you, I will try to fix the issue using your file. I suspect it may be something else now, seeing that the file size is not so big, but it is tbc

**Comment by blurymind** [comment]
silly question, but are you using the massively outdated electron version or the web version of the editor?

**Comment by AlekFy** [comment]
There is no way to Ctrl+S (save) in the web editor, because it does not work on the local file but an online copy. I only can Save As using the menu so it's not the same case. Also it's not available anymore (404) :(

**Comment by blurymind** [comment]
i think it is possible to bring the ctrl+s same file writing to the progressive web app version too, it just needs some dev work

**Comment by blurymind** [comment]
I have now addressed this in the PWA version of yarn via
https://github.com/blurymind/YarnClassic/commit/c7694e2b05617c6cbe2078600c21c2ee169fa667

you can also install and use it offline as a PWA.

If you now open a local file or save a file- Yarn will keep its handle and every time you click on the save icon (bottom left)
yarn will override the same file instead of downloading it as a new file

**Comment by blurymind** [comment]
I have also assigned this to ctrl+s if you dont like the save button
https://github.com/blurymind/YarnClassic/commit/5375d33c88b98127bee753594c57c43c13c92ba0

**Comment by AlekFy** [comment]
(Sorry for the delayed response) Thank you for those improvements, it helps a lot! I've made a PWA on my desktop, works really well if I set redraw delay to 0 I can't really feel the difference from the electron version. The gist approach seems the most convenient! Thank you blurymind!
