### ISSUE TITLE
Have an option to have the Yarn Editor open with a new file each time

### ISSUE THREAD

**Issue by Subliminalman** [blurymind/YarnClassic#323]
This may end up being two separate things but it would be nice to have a settings option to have the editor open a new file when first opening instead of the cached file. The reason for me is that I will be working between two stations and pushing to git my yarn files and the editor won't reflect the latest changes, rather the internal cache it has of the file. I would prefer to have the option to start with a new file and open for safety knowing I'm opening the correct working file. The separate issue would be reading the correct file instead of the cached one in Yarn Editor memory.

**Comment by blurymind** [comment]
yup that is actually not a bad idea. Think we can add something in the settings window

**Comment by AlekFy** [comment]
+1 :)

**Comment by blurymind** [comment]
I think I would actually even disable this feature entirely for electron - as it could hinder it in gdevelop

**Comment by blurymind** [comment]
I implemented this, but somehow managed to break file saving in the PWA version in doing so. I will do a fix asap
